# Generated by Django 3.2.7 on 2022-01-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='describtion',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='description', max_length=250),
        ),
    ]
